"""Type stubs for dynamically loaded ops — 让 Pylance 能识别。"""

import torch

def linear(x: torch.Tensor, weight: torch.Tensor, bias: torch.Tensor,
           *, compute: str | None = None, output_dtype: str | None = None) -> torch.Tensor: ...

def matmul(x: torch.Tensor, weight: torch.Tensor,
           *, compute: str | None = None, output_dtype: str | None = None) -> torch.Tensor: ...

def layernorm1d(x: torch.Tensor, gamma: torch.Tensor, beta: torch.Tensor,
                *, compute: str | None = None, output_dtype: str | None = None) -> torch.Tensor: ...

def transpose(x: torch.Tensor, dim0: int = -2, dim1: int = -1,
              *, compute: str | None = None, output_dtype: str | None = None) -> torch.Tensor: ...

def list_ops() -> list[str]: ...
def dispatch(op_name: str, *args, **kwargs) -> torch.Tensor: ...
def register_op(_func=None, *, golden_c: dict = None, math_strategy=None, **default_formats): ...
def set_ops_hooks(**hooks) -> None: ...
